UWEFlix/urls.py
from django.urls import path
from . import views

# URLConf
urlpatterns = [
    # path('navbar/', name='navbar'),
    path('films/', views.show_films, name='films'),
    path('index/', views.index, name='index'),
    path('', views.index, name='nopath'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.login_user, name='logout'),
    path('register_user/', views.register_user, name='register_user'),
    path('showings/', views.show_showings, name='showings'),
    path('screens/', views.show_screens, name='screens'),
    path('clubs/', views.show_clubs, name='clubs'),
    path('club_representatives/', views.show_clubs_reps, name='club_representatives'),
    path('add_film/', views.add_film, name='add_film'),
    path('add_showing/', views.add_showing, name='add_showing'),
    path('add_screen/', views.add_screen, name='add_screen'),
    path('add_club/', views.register_club, name='add_club'),
    path('update_film/<film_id>/', views.update_film, name='update_film'),
    path('update_screen/<screen_id>/', views.update_screen, name='update_screen'),
    path('update_club_representative/<clubrepresentative_id>/', views.update_club_representative, name='update_club_representative'),
    path('delete_film/<film_id>', views.delete_film, name='delete_film'),
    path('elevate_user/', views.elevate_user, name='elevate_user')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('UWEFlix/', include('django.contrib.auth.urls')),
    path('', include('UWEFlix.urls')),
]

UWEFlix/models.py
from django.contrib.auth.models import User
from django.conf import settings
#from django.utils.crypto import get_random_string
from django.db import models


# cinema side

class Film(models.Model):
    name = models.CharField(max_length=255)
    age_rating = models.PositiveSmallIntegerField()
    duration = models.DecimalField(max_digits=5, decimal_places=2)
    short_trailer_description = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

class Screen(models.Model):
    screen_number = models.PositiveSmallIntegerField(unique=True)
    capacity = models.PositiveIntegerField()

    def __str__(self) -> str:
        return str(self.screen_number)


class Showing(models.Model):
    film = models.ForeignKey(Film, on_delete=models.PROTECT)
    screen = models.ForeignKey(Screen, on_delete=models.PROTECT)
    time = models.DateTimeField()

class Ticket(models.Model):
    TICKET_TYPE_STUDENT = 'S'
    TICKET_TYPE_ADULT = 'A'
    TICKET_TYPE_CHILD = 'C'

    TICKET_TYPE_CHOICE = [
        (TICKET_TYPE_STUDENT, 'Student'),
        (TICKET_TYPE_ADULT, 'Adult'),
        (TICKET_TYPE_CHILD, 'Child'),
    ]

    ticket_type = models.CharField(max_length=1, choices=TICKET_TYPE_CHOICE, default=TICKET_TYPE_STUDENT)

    showing = models.ForeignKey(Showing, on_delete=models.PROTECT)

    PRICE_CHOICE = [
        (TICKET_TYPE_STUDENT, '10'),
        (TICKET_TYPE_ADULT, '15'),
        (TICKET_TYPE_CHILD, '5'),
    ]

    ticket_price = models.CharField(max_length=1, choices=PRICE_CHOICE)

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    showing = models.OneToOneField(Showing, on_delete=models.DO_NOTHING, null=True)

class BookingItem(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

class Address(models.Model):
    street_number = models.CharField(max_length=50)
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    postcode = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.street_number + ' ' + self.street


class ContactDetails(models.Model):
    mobile_number = models.CharField(max_length=50)
    landline_number = models.CharField(max_length=50)
    email = models.EmailField(unique=True)

    def __str__(self) -> str:
        return self.email

class PaymentDetails(models.Model):
    card_name = models.CharField(max_length=255)
    card_number = models.CharField(max_length=255)
    expiry_date = models.DateField()


# club side

class Club(models.Model):
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
    contact_details = models.ForeignKey(ContactDetails, on_delete=models.CASCADE, null=True)
    club_name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.club_name

class ClubRepresentative(models.Model):
    club = models.OneToOneField(Club, on_delete=models.CASCADE, related_name='clubRep')
    birth_date = models.DateField()
    club_representative_number = models.IntegerField(unique=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return self.user.first_name + ' ' + self.user.last_name

    

class Account(models.Model):
    club = models.OneToOneField(Club, on_delete=models.PROTECT)
    payment_details = models.ForeignKey(PaymentDetails, on_delete=models.CASCADE)
    account_title = models.CharField(max_length=255, primary_key=True)
    discount_rate = models.DecimalField(max_digits=5, decimal_places=2)


# unsure about this class, made it to keep a list of all accounts
class Order(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.PROTECT)
    account = models.OneToOneField(Account, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    # class Meta:
    #     odering - ['user__first_name', 'user__last_name']

UWEFlix/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import DateInput
from .models import *


# forms.form -> creating form from scratch
# forms.Modelform -> from models


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['name', 'age_rating', 'duration', 'short_trailer_description']

class ScreenForm(forms.ModelForm):
    class Meta:
        model = Screen
        fields = ['screen_number', 'capacity']

class ShowingForm(forms.ModelForm):
    time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    class Meta:
        model = Showing
        fields = ['time', 'film', 'screen']


# club representative form required


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['club_name']

class ClubRepresentativeForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    # user = forms.ModelChoiceField(queryset=User.objects.all())
    class Meta:
        model = ClubRepresentative
        fields = ['first_name', 'last_name', 'birth_date']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'datepicker'})
        }

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street_number', 'street', 'city', 'postcode']

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactDetails
        fields = ['landline_number', 'mobile_number', 'email']


class ElevateUserForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all())
    group = forms.ChoiceField(choices=[
        ('CinemaManager', 'Cinema Manager')
    ])

    class Meta:
        model = User
        fields = ['user', 'group']

UWEFlix/views.py
from django.shortcuts import render, redirect
from django.utils.crypto import get_random_string
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.db.models import Sum, Count
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from .forms import *
from datetime import datetime
from django.utils import timezone
import random

# Create your views here.
# request -> response
# request handler
# action

# def show_films(request):

#     queryset = Film.objects.all()

#     return render(request, 'UWEFlix/films.html', {'films': list(queryset)})
def check_permissions(request):
    if request.user.groups.filter(name='CinemaManager').exists(): #checks if user is in Cinema Managers django group
        permlevel = 1 # sets 1 if yes
    else:
        permlevel = 0
    return permlevel #returns value to orignal function


def index(request):
    permlevel = check_permissions(request)
    return render(request, 'UWEFlix/index.html', {'permlevel': permlevel})

def elevate_user(request):
    permlevel = check_permissions(request)

    #     # Only allow users who are already in the Cinema Managers group to access this page
    # if not request.user.groups.filter(name='CinemaManager').exists():
    #     return redirect('index')

    # Get all users who are not already in the Cinema Managers group
    users = User.objects.exclude(groups__name='Cinema Managers')

    if request.method == 'POST':
        # Get the user that the logged in user wants to add to the group
        user_id = request.POST['user']
        user = User.objects.get(id=user_id)

        # Add the user to the Cinema Managers group
        group = Group.objects.get(name='CinemaManager')
        group.user_set.add(user)

        return redirect('index')

    context = {'users': users, 'user': request.user, 'users': User.objects.all(), 'permlevel': permlevel}
    return render(request, 'UWEFLix/elevate_user.html', context)

def show_films(request):
    permlevel = check_permissions(request)

    queryset = Film.objects.all().prefetch_related('showing_set')
    return render(request, 'UWEFlix/films.html', {'films': list(queryset), "permlevel":permlevel})


def add_film(request):
    submitted = False
    if request.method == "POST":
        form = FilmForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = FilmForm
        if 'submitted' in request.GET:
            submitted = True

    # form = FilmForm
    return render(request, 'UWEFlix/add_film.html', {'form': form, 'submitted':submitted})

def add_screen(request):
    submitted = False
    if request.method == "POST":
        form = ScreenForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = ScreenForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'UWEFlix/add_screen.html', {'form': form, 'submitted':submitted})

def add_showing(request):
    submitted = False
    if request.method == "POST":
        form = ShowingForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = ShowingForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'UWEFlix/add_showing.html', {'form': form, 'submitted':submitted})


def register_club(request):
    submitted = False
    #password = ''
    if request.method == "POST":
        club_form = ClubForm(request.POST)
        club_representative_form = ClubRepresentativeForm(request.POST)
        address_form = AddressForm(request.POST)
        contact_form = ContactForm(request.POST)
        if club_representative_form.is_valid() and club_form.is_valid() and address_form.is_valid() and contact_form.is_valid():
            club = club_form.save()
            club_representative = club_representative_form.save(commit=False)
            club_representative.club = club
            address_form.save()
            contact_form.save()

            # random_number =  ClubRepresentative.objects.club_representative_number(int(get_random_string(length=10, allowed_chars='1234567890')))

            # while ClubRepresentative.objects.filter(ClubRepresentative__club_representative_number=random_number):
            #     random_number =  ClubRepresentative.objects.club_representative_number(int(get_random_string(length=10, allowed_chars='1234567890')))

            ClubRepresentative.objects.club_representative_number = random.randint(2345678909800, 9923456789000)

            club_representative.club_representative_number = get_random_string(length=10, allowed_chars='0123456789')
            club_representative.user = User.objects.create_user(username=club_representative_form.cleaned_data['first_name'],password=get_random_string(length=8))
            club_representative.user.first_name = club_representative_form.cleaned_data['first_name']
            club_representative.user.last_name = club_representative_form.cleaned_data['last_name']
            club_representative.user.save()
            club_representative.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        club_form = ClubForm
        club_representative_form = ClubRepresentativeForm
        address_form = AddressForm
        contact_form = ContactForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'UWEFlix/add_club.html', {
        'club_form': club_form,
        'club_representative_form': club_representative_form,
        'address_form': address_form,
        'contact_form': contact_form,
        'submitted': submitted,
    })


def update_film(request, film_id):
    film = Film.objects.get(pk=film_id)
    form = FilmForm(request.POST or None, instance=film)
    if form.is_valid():
        form.save()
        return redirect('films')
    return render(request, 'UWEFlix/update_film.html', {'film':film, 'form':form})

def update_screen(request, screen_id):
    screen = Screen.objects.get(pk=screen_id)
    form = ScreenForm(request.POST or None, instance=screen)
    if form.is_valid():
        form.save()
        return redirect('screens')
    return render(request, 'UWEFlix/update_screen.html', {'screen':screen, 'form':form})

# update club here


def update_club_representative(request, clubrepresentative_id):
    clubrepresentative = Screen.objects.get(pk=clubrepresentative_id)
    form = ScreenForm(request.POST or None, instance=clubrepresentative)
    if form.is_valid():
        form.save()
        return redirect('club_representatives')
    return render(request, 'UWEFlix/update_club_representative.html', {'clubrepresentative':clubrepresentative, 'form':form})



def show_showings(request):
    queryset = Showing.objects.all()

    return render(request, 'UWEFlix/showings.html', {
        'showings': list(queryset)
    })

def show_screens(request):
    queryset = Screen.objects.all()

    return render(request, 'UWEFlix/screens.html', {
        'screens': list(queryset)
    })

def show_clubs(request):
    queryset = Club.objects.all()

    return render(request, 'UWEFlix/clubs.html', {
        'clubs': list(queryset)
    })

def show_clubs_reps(request):
    queryset = ClubRepresentative.objects.all()

    return render(request, 'UWEFlix/club_representatives.html', {
        'club_reps': list(queryset)
    })

def delete_film(request, film_id):

    film = Film.objects.get(pk=film_id)
    film.delete()
    return redirect('films')



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('films')
        else:
            messages.success(request, ("there was an error logging in, try again"))
            return redirect('login')
    else:
        return render(request, 'UWEFlix/login.html', {})

def logout_user(request):
    logout(request)
    messages.success("you have been logged out")
    return redirect('films')

def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ('Registration Successful'))
            return redirect('films')
    else:
        form = UserCreationForm()
    return render(request, 'UWEFlix/register_user.html', {
        'form': form,
    })







    

    

    

UWEFlix/templates/UWEFlix/add_club.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <center>
        <h1>Register Club</h1>
        <br>

        {% if submitted %}
          The Club Representative Password is: <br>
          {{ password }}

        {% else %}

        <form action="" method=POST>
        {% csrf_token %}

        <h1>Club</h1>

          {{ club_form.as_p }}

          <h1>Club Address</h1>

          {{ address_form.as_p }}

          <h1>Club Contact Details</h1>

          {{ contact_form.as_p }}

          <h1>Club Representative Details</h1>

          {{ club_representative_form.as_p }}

          <input type="submit" value="Submit" class="btn btn-success">

        </form>
      {% endif %}
    </center>

  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/add_film.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <center>
        <h1>Add Film</h1>
        <br>

        {% if submitted %}
          Your Film was added successfully

        {% else %}

        <form action="" method=POST>
        {% csrf_token %}

          {{form.as_p }}

          <input type="submit" value="Submit" class="btn btn-success">

        </form>
      {% endif %}
    </center>

  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/add_screen.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <center>
        <h1>Add Screen</h1>
        <br>

        {% if submitted %}
          Your Screen was added successfully

        {% else %}

        <form action="" method=POST>
        {% csrf_token %}

          {{form.as_p }}

          <input type="submit" value="Submit" class="btn btn-success">

        </form>
      {% endif %}
    </center>

  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/clubs.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <h1>Clubs</h1>

    <a href="{% url 'add_club' %}" class="btn btn-primary add-film-btn">Register a new club</a>
    <br><br>

      {% for club in clubs %}
        <div class="film-box">
          <div>
            <h3>{{ club.club_name }}</h3>
            <li>Club ID: {{ club.id }}</li>
            <li>Club rep: {{ club.clubRep.first_name }}</li>

            <br><br>
            {% comment %} {% url 'modify_film' film.id %} {% endcomment %}
            <a href="#" class="btn btn-secondary modify-film-btn">Modify Club Details</a>
            {% comment %} {% url 'delete_film' film.id %} {% endcomment %}
            <a href="#" class="btn btn-danger delete-film-btn" onclick="return confirm('Are you sure you want to delete this film?');">Delete Club</a>

          </div>
        </div>
          <br><br>
      {% endfor %}
  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/elevate_user.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<div class="container mt-5">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="card mt-5">
    <div class="card-header">
        <h5>Add User to Cinema Manager Role</h5>
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'elevate_user' %}">
            {% csrf_token %}
            <div>
                <label for="id_user">Select User:</label>
                <select name="user" id="id_user">
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Add User to Cinema Managers</button>
        </form>
    </div>
</div>

</div>


{% endblock %}

UWEFlix/templates/UWEFlix/films.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <h1>Films</h1>

    {% comment %} {% url 'add_film' %} {% endcomment %}
    <a href="{% url 'add_film' %}" class="btn btn-primary add-film-btn">Add Film</a>
    <br><br>



      {% for film in films %}
        <div class="film-box">
          <div>
            <h3>{{ film.name }}</h3>
            <li>{{ film.duration }}</li>
            <li>{{ film.age_rating }}</li>
            <li>{{ film.short_trailer_description }}</li>
            
            <br><br>    
            <a href="{% url 'update_film' film.id %}" class="btn btn-secondary modify-film-btn">Modify Film Details</a>
            
            {% if permlevel %}
            <a href="{% url 'delete_film' film.id %}" class="btn btn-danger delete-film-btn" onclick="return confirm('Are you sure you want to delete this film?');" >Delete Film</a>
            {% endif %}

          </div>
        </div>
          <br><br>
      {% endfor %}
  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/index.html
{% extends 'UWEFlix/navbar.html' %}
{% block content %}
{% endblock %}

UWEFlix/templates/UWEFlix/login.html
<html>
    <head>
      <link rel="stylesheet" href="/static/login.css">
    </head>
    <body>
        {% block content %}

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}

        <h1>Login</h1>
        <form action="" method=POST>
            {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Username</label>
                  <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  <input type="password" class="form-control" name="password">
                </div>
            <input type="submit" value="Submit" class="btn btn-secondary">
        </form>
        {% endblock %}
    </body>
</html>

 

UWEFlix/templates/UWEFlix/navbar.html
<html>
    <head>
        <link rel="stylesheet" href="/static/navbar.css">
    </head>
    <body>
        <ul class="nav-list">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'films' %}">Films</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register_user' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'showings' %}">Showings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'screens' %}">Screens</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'clubs' %}">Clubs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'club_representatives' %}">Club Representatives</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'elevate_user' %}">Elevate User</a>
            </li>
        </ul>
    </body>
</html>

{% block content %} {% endblock %}

UWEFlix/templates/UWEFlix/register_user.html
<html>
    <head>
      <link rel="stylesheet" href="/static/login.css">
    </head>
    <body>
        {% block content %}

        <h1>Register</h1>
        
        <form action="{% url 'register_user' %}" method=POST>
            {% csrf_token %}

            {{ form.as_p}}
            
            <input type="submit" value="Submit" class="btn btn-secondary">
        </form>
        {% endblock %}
    </body>
</html>

 

UWEFlix/templates/UWEFlix/screens.html
{% extends 'UWEFlix/navbar.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <h1>Screens</h1>

    <a href="{% url 'add_screen' %}" class="btn btn-primary add-film-btn">Add Screen</a>
    <br><br>

      {% for screen in screens %}
        <div class="film-box">
          <div>
            <li>Screen: {{ screen.screen_number }}</li>
            <li>Capacity: {{ screen.capacity }}</li>

            <br><br>
            {% comment %} {% url 'modify_film' film.id %} {% endcomment %}
            <a href="{% url 'update_screen' screen.id %}" class="btn btn-secondary modify-film-btn">Modify Screen Details</a>
            {% comment %} {% url 'delete_film' film.id %} {% endcomment %}
            <a href="#" class="btn btn-danger delete-film-btn" onclick="return confirm('Are you sure you want to delete this film?');">Delete Screen</a>

          </div>
        </div>
          <br><br>
      {% endfor %}
  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/showings.html
{% extends 'UWEFlix/navbar.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <h1>Showings</h1>

    <a href="{% url 'add_showing' %}" class="btn btn-primary add-film-btn">Add Showing</a>
    <br><br>

      {% for showing in showings %}
        <div class="film-box">
          <div>
            <h3>{{ showing.film.name }}</h3>
            <li>age rating: {{ showing.film.age_rating }}</li>
            <li>description: {{ showing.film.short_trailer_description }}</li>
            <li>{{ showing.time }}</li>
            <li>screen number: {{ showing.screen.screen_number }}</li>
            <li>capacity: {{ showing.screen.capacity }}</li>
            {% comment %} <li>{{ film.shortTrailerDescription }}</li> {% endcomment %}
          </div>
        </div>
          <br><br>
      {% endfor %}
  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/update_club_representative.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <center>
        <h1>Update Club Represenative</h1>
        <br>

       

        <form action="" method=POST>
        {% csrf_token %}

          {{form.as_p }}

          <input type="submit" value="Update" class="btn btn-success">

        </form>
    </center>

  </body>
</html>
{% endblock %}

UWEFlix/templates/UWEFlix/update_film.html
{% extends 'UWEFlix/navbar.html' %}

{% block content %}

<html>
  <head>
    <link rel="stylesheet" href="/static/films.css">
  </head>
  <body>
    <center>
        <h1>Update Film</h1>
        <br>

       

        <form action="" method=POST>
        {% csrf_token %}

          {{form.as_p }}

          <input type="submit" value="Update" class="btn btn-success">

        </form>
    </center>

  </body>
</html>
{% endblock %}